using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[System.Serializable]
public class Level
{
    // The grid of tiles of the level
    public List<List<Tile>> tileMatrix;

    // The name of the level
    public string levelName;

    // Was the level generated by the player in the arena editor?
    public bool custom;

    public int Height
    {
        get
        {
            return tileMatrix.Count;
        }
    }

    public int Width
    {
        get
        {
            return tileMatrix[0].Count;
        }
    }

    // An empty level
    public static Level EmptyLevel(int height, int width)
    {
        Level output = new()
        {
            tileMatrix = new()
        };

        for (int i = 0; i < height; i++)
        {
            List<Tile> row = new();
            for (int j = 0; j < width; j++)
            {
                Tile tile = new()
                {
                    closed = i == 0 || i + 1 == height || j == 0 || j + 1 == width
                };
                
                row.Add(tile);
            }
            output.tileMatrix.Add(row);
        }
        return output;
    }

    public Level Clone()
    {
        Level output = new();
        output.levelName = levelName;
        output.custom = custom;
        List<List<Tile>> outputTileMatrix = new();
        for (int i = 0; i < Height; i++)
        {
            List<Tile> row = new();
            for (int j = 0; j < Width; j++)
            {
                row.Add(tileMatrix[i][j].Clone());
            }
            outputTileMatrix.Add(row);
        }
        output.tileMatrix = outputTileMatrix;
        return output;
        
    }

    public string DebugDescription()
    {
        string output = "";
        for (int i = 0; i < Height; i++)
        {
            for (int j = 0; j < Width; j++)
            {
                output +=  tileMatrix[i][j].DebugDescription();
            }            
            output += "\n";
        }
        return output;

    }
}